server:
  port:
    8002
#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3307/nassafy?characterEncoding=UTF-8&serverTimezo  # local에서는 localhost로 사용, 코드 올릴 때는 서버 database로 변경
#    username: root
#    password: ssafy0103!  # local에서는 각자 비밀번호로 변경하고, 올릴 때는 ssafy1234!로 변경하기
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
