server:
  port: 8000

# 기본 로그 레벨 설정
logging:
  level:
    root: warn
    com.nassafy.api: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
#logging:
#  level:
#    ccom.nassafy.api: info    # 로깅 레벨

spring:

#  h2:
#    console:
#      enabled: true


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/nassafy  # local에서는 localhost로 사용, 코드 올릴 때는 서버 database로 변경
    username: root
    password: ssafy1234!  # local에서는 각자 비밀번호로 변경하고, 올릴 때는 ssafy1234!로 변경하기

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: ckstjr93@gmail.com #앱 비밀번호 발급받은 google 계정
    password: isemeuihjvftkkwx #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

