server:
  # 프로젝트 환경의 포트 설정
  port: 8000

# 기본 로그 레벨 설정
logging:
  level:
    root: warn
    com.nassafy.api: info
    org.hibernate.type.descriptor.sql: trace

spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      #SessionFactory가 시작될때 Drop, Create, Alter / 종료될 때 Drop
      ddl-auto: create-drop
    properties:
      hibernate:
        # Console에서 실행되는 sql을 보기좋게 보여주는 설정
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

