server:
  port: 8000

# 기본 로그 레벨 설정
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    root: warn
    com.nassafy.api: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    org:
      springframework:
        web:
          filter: debug

#logging:
#  level:
#    ccom.nassafy.api: info    # 로깅 레벨



spring:
  #  h2:
  #    console:
  #      enabled: true
  config:
    activate:
      on-profile: prod
  s3:
    bucket: nassafy
    access-key: AKIA6RPAGTVSAHG42EQ2
    secret-key: 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

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database:3306/nassafy
    username: root
    password: ssafy1234!

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 100MB  # 요청한 파일 한 개의 크기
      max-request-size: 100MB  # 요청한 파일 전체의 크기

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: ckstjr93@gmail.com #앱 비밀번호 발급받은 google 계정
    password: isemeuihjvftkkwx #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false