server:
  port: 8001

# 기본 로그 레벨 설정
logging:
  level:
    root: warn
    com.nassafy.batch: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    org:
      springframework:
        web:
          filter: DEBUG

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database:3306/nassafy
    username: root
    password: ssafy1234!
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
  redis:
    host: redis
    port: 6379
    password: ssafy1234!
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

fcm :
  key :
    scope : https://www.googleapis.com/auth/cloud-platform
    #
    path : nassafy-push-test-firebase-adminsdk-tsno6-c5364d0263.json
  api_url : https://fcm.googleapis.com/v1/projects/nassafy-push-test/messages:send
  fcm_token : ejVFij7mTwqxt6Z2tO2q-O:APA91bGhCQtXGmonPI6T3aB0CF2peRsxXJpE28PKgehZ6zw13FcWqSg3YlvtSbFkbv3gb7Zt2p7LKhQStOA10dWbiogMW8M_ZWV2IdiNeyNq7_OV-KrIPOKTRQI3QlcYmsB3lWRgAGwk
  projectID : nassafy-push-test

#    path :  nassafy-aro-firebase-adminsdk-b1oip-f2accc8ad7.json
#  api_url : https://fcm.googleapis.com/v1/projects/nassafy-aro/messages:send
#  fcm_token : db3r620YQJqiM-EIRmy8qY:APA91bHy0O6eAsDoNw-voc8-sdWte-LRBVNZulsZ4WLqgL9zE3U0S8Kswd-rAQg7eTtnuYOoTVfDmHHUEifxBQqgdehPOyr__zrj7ybq_wpV0yj2Ac0tk8d4sWmiwPpRUan0VjgYnhcm
#  projectID: nassafy-aro
