server:
  port: 8001

# 기본 로그 레벨 설정
logging:
  level:
    root: warn
    com.nassafy.batch: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG

openweathermap:
  api-key: bde174932a0010cfd281d38a28820cb2
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/ko?characterEncoding=UTF-8&serverTimezone
    username: ming
    password: ssafy1234!  # local에서는 각자 비밀번호로 변경하고, 올릴 때는 ssafy1234!로 변경하기
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
  redis:
    host: j8d106.p.ssafy.io
    port: 6379
    password: ssafy1234!
  batch:
    job:
      enabled: false   # batch server 실행시켰을 때, 실행되는지 아닌지
    jdbc:
      isolation-level-for-create: default  # batch meta data table이 자동으로 생성되는지 아닌지
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400



