server:
  port: 8001

# 기본 로그 레벨 설정
logging:
  level:
    root: warn
    com.nassafy.api: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    org:
      springframework:
        web:
          filter: DEBUG

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database:3306/nassafy
    username: root
    password: ssafy1234!
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
  redis:
    host: redis
    port: 6379
    password: ssafy1234!
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
openweathermap:
  api-key: bde174932a0010cfd281d38a28820cb2